name: EnchantmentsDisabler
main: Saiini\EnchantmentsDisabler\EnchantmentsDisabler
version: 1.0.0
api: 3.0.0
website: https://github.com/Saiini
author: Saiini
depend: PiggyCustomEnchants

# All the credit goes to Saiini.. Idk what happened to his repo but I had an old fork so I updated it.
# He changed his username from Saiini14 TV to Saiin.